services:
  httpenv:
    image: "${TESTING_IMAGE}"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: "10s"
      timeout: "5s"
      retries: 5
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      httpenv:
        condition: service_started
      postgres:
        condition: service_healthy
    # run all your tests here against the httpenv service
    command: curl --fail http://httpenv:8888 || exit 1